### ISSUE TITLE
Trouble with the v2 prices

### ISSUE THREAD

**Issue by franzo9448** [bobbypine/Rolex#1]
Hello, I'm having issues with pricesv2. Currently, from what I understand, it's unable to retrieve information via bs4. I would be grateful if you could help me with this.

**Comment by bobbypine** [comment]
V2 uses Selenium, not bs4. Its inclusion in the import statement is a mistake, I just never deleted it after moving it to selenium.

**Comment by franzo9448** [comment]
thanks for the answer , i re rurrned the prices v2 i am getting this errors 

  File "Prices_V2.py", line 73, in <module>
    run()
  File "Code\Prices_V2.py", line 60, in run
    obs = prices(x)
          ^^^^^^^^^
  File "Prices_V2.py", line 44, in prices
    data[ref] = data[ref].str.replace('\n', '', regex=False).str.replace('$', '', regex=False).str.replace(',', '',
                ~~~~^^^^^
  File "site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: '126610LN'

**Comment by bobbypine** [comment]
Make sure you have the appropriate version of chromedriver for your browser and its location is in the DRIVER_PATH variable (line 31). Also in the future please don’t use this as a thread for local issues.
